tabWidth: 4
semi: false
singleQuote: true
jsxSingleQuote: true
trailingComma: all
overrides:
  - files:
      - '*.yml'
      - '*.yaml'
      - '*.json'
      - '*.prisma'
    options:
      tabWidth: 2
